package minesweeper

fun main() {
    print("""
        .X.......
        .....X..X
        ....X....
        ......X..
        ..X......
        ....X....
        ..X......
        ..X......
        ......X..
    """.trimIndent())
}
